version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Build solution
          command: dotnet build --configuration Release src
      - persist_to_workspace:
          root: .
          paths: 
            - ./*
  unit tests:
    working_directory: ~/build
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Tests
          command: dotnet test -v normal --configuration Release --no-build src/Feree.ResultType.Tests/
  integration tests:
    working_directory: ~/build
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Tests
          command: dotnet test -v normal --configuration Release --no-build src/Feree.ResultType.IntegrationTests/
  nuget:
    working_directory: ~/build
    docker:
      - image: mono:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Update nuget
          command: nuget update -self
      - run:
          name: Pack
          command: nuget pack package/Feree.ResultType.nuspec -properties Configuration=Release
workflows:
  version: 1
  build_and_test:
    jobs:
      - build
      - unit tests:
          requires:
            - build
      - integration tests:
          requires:
            - build
      - nuget:
          filters:
            branches:
              only: deploy
          requires:
            - unit tests
            - integration tests